Add status-check job in the GH Actions workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,8 +13,7 @@ jobs:
   changes:
     runs-on: ubuntu-latest
     outputs:
-      src: ${{ steps.filter.outputs.src }}
-      tests: ${{ steps.filter.outputs.tests }}
+      has-changes: ${{ steps.filter.outputs.has-changes }}
     steps:
       - name: Check out
         uses: actions/checkout@v4
@@ -23,9 +22,8 @@ jobs:
         id: filter
         with:
           filters: |
-            src:
+            has-changes:
               - 'src/**'
-            tests:
               - 'tests/**'
 
   lint:
@@ -51,8 +49,8 @@ jobs:
           pre-commit run --all-files --show-diff-on-failure
 
   test:
-    needs: changes
-    if: ${{ needs.changes.outputs.src == 'true' || needs.changes.outputs.tests == 'true' }}
+    needs: [changes]
+    if: ${{ needs.changes.outputs.has-changes == 'true' }}
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -76,3 +74,14 @@ jobs:
       - name: Run pytest
         run: |
           pytest tests -n auto
+
+  status-check:
+    if: always()
+    needs: [lint, test]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check results
+        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        run: |
+          echo "Status check failed for one or more jobs"
+          exit 1
